# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIKitty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIKitty
  pod 'ADragDropView'
  pod 'XMLCoder'
  pod 'SwiftyXML'
  pod 'xcodeproj', '~> 7.19.0'
  
end
